apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-access
spec:
  podSelector:
    matchLabels:
      app: flask-api
  ingress:
  - from:
    - ipBlock:
        cidr: 172.24.0.26/24  # IP client (VM1)
